HL_SIZE = 1  # Hidden layer size
INPUT_SEQ_LENGTH = 30  # Length of input sequences after zero-padding is applied
CLASS_INDICES = {3: 0, 4:1, 5:2}  # Our current dataset spans only three grades: 3, 4, and 5
MODEL_PATH = './model.h5'
LOAD_OLD = False  # Pick up from saved checkpoint
EPOCHS = 15
LR = 1e-3  # Learning rate
BATCH_SIZE = 6
DATA_PATH = './Images/'
VAL_SPLIT = .2  # Note: At present, only 46 data points are available
