HL_SIZE = 1  # Hidden layer size
INPUT_SEQ_LENGTH = 30  # Length of input sequences after zero-padding is applied
N_CLASSES = 5
MODEL_PATH = './model.h5'
EPOCHS = 1000
LR = 1e-3  # Learning rate
BATCH_SIZE = 5
DATA_PATH = './Images/'
EVAL_SET_SIZE = 10  # Note: At present, only 46 data points are available
